//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package ietf.params.xml.ns.icalendar_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfVcalendarContainedComponents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfVcalendarContainedComponents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}vcalendarContainedComponent" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfVcalendarContainedComponents", propOrder = {
    "vcalendarContainedComponent"
})
public class ArrayOfVcalendarContainedComponents {

    @XmlElementRef(name = "vcalendarContainedComponent", namespace = "urn:ietf:params:xml:ns:icalendar-2.0", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends VcalendarContainedComponentType>> vcalendarContainedComponent;

    /**
     * Gets the value of the vcalendarContainedComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vcalendarContainedComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVcalendarContainedComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link VtodoType }{@code >}
     * {@link JAXBElement }{@code <}{@link WsCalendarIntervalType }{@code >}
     * {@link JAXBElement }{@code <}{@link VtimezoneType }{@code >}
     * {@link JAXBElement }{@code <}{@link VcalendarContainedComponentType }{@code >}
     * {@link JAXBElement }{@code <}{@link WsCalendarGluonType }{@code >}
     * {@link JAXBElement }{@code <}{@link VeventType }{@code >}
     * {@link JAXBElement }{@code <}{@link VavailabilityType }{@code >}
     * {@link JAXBElement }{@code <}{@link VjournalType }{@code >}
     * {@link JAXBElement }{@code <}{@link VfreebusyType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends VcalendarContainedComponentType>> getVcalendarContainedComponent() {
        if (vcalendarContainedComponent == null) {
            vcalendarContainedComponent = new ArrayList<JAXBElement<? extends VcalendarContainedComponentType>>();
        }
        return this.vcalendarContainedComponent;
    }

    public boolean isSetVcalendarContainedComponent() {
        return ((this.vcalendarContainedComponent!= null)&&(!this.vcalendarContainedComponent.isEmpty()));
    }

    public void unsetVcalendarContainedComponent() {
        this.vcalendarContainedComponent = null;
    }

}
