//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power.resource;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ietf.params.xml.ns.icalendar_2.DurationPropType;
import org.oasis_open.docs.ns.emix._2011._06.power.PowerAttributesType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oasis_open.docs.ns.emix._2011._06.power.resource package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MaximumResponse_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "maximumResponse");
    private final static QName _OfferCurve_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "offerCurve");
    private final static QName _ResourceType_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "resourceType");
    private final static QName _DispatchUp_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "dispatchUp");
    private final static QName _PMax_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "pMax");
    private final static QName _EndRamp_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "endRamp");
    private final static QName _DispatchTime_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "dispatchTime");
    private final static QName _OfferSegment_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "offerSegment");
    private final static QName _RegulationService_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "regulationService");
    private final static QName _PowerRampSegment_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "powerRampSegment");
    private final static QName _StagingRamp_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "stagingRamp");
    private final static QName _Window_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "window");
    private final static QName _MaximumDeliveryRate_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "maximumDeliveryRate");
    private final static QName _LoadReduction_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "loadReduction");
    private final static QName _MinimumResponse_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "minimumResponse");
    private final static QName _PowerResponse_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "powerResponse");
    private final static QName _PercentRampRate_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "percentRampRate");
    private final static QName _QMax_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "qMax");
    private final static QName _RecoveryRamp_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "recoveryRamp");
    private final static QName _Rate_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "rate");
    private final static QName _PowerRamp_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "powerRamp");
    private final static QName _MinimumLoad_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "minimumLoad");
    private final static QName _Generation_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "generation");
    private final static QName _MaximumEnergy_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "maximumEnergy");
    private final static QName _MinimumLoadReduction_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "minimumLoadReduction");
    private final static QName _ProductTypeRegulation_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "productTypeRegulation");
    private final static QName _TargetRegulation_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "targetRegulation");
    private final static QName _ActiveReserve_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "activeReserve");
    private final static QName _DispatchDown_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "dispatchDown");
    private final static QName _RampSegments_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "rampSegments");
    private final static QName _MinimumDeliveryRate_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "minimumDeliveryRate");
    private final static QName _VMin_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "vMin");
    private final static QName _ProductVoltageRegulation_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "productVoltageRegulation");
    private final static QName _BeginRamp_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "beginRamp");
    private final static QName _VMax_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "vMax");
    private final static QName _RampTime_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "rampTime");
    private final static QName _MaximumPower_QNAME = new QName("http://docs.oasis-open.org/ns/emix/2011/06/power/resource", "maximumPower");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis_open.docs.ns.emix._2011._06.power.resource
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfRampSegments }
     * 
     */
    public ArrayOfRampSegments createArrayOfRampSegments() {
        return new ArrayOfRampSegments();
    }

    /**
     * Create an instance of {@link ActiveReserveType }
     * 
     */
    public ActiveReserveType createActiveReserveType() {
        return new ActiveReserveType();
    }

    /**
     * Create an instance of {@link ProductVoltageRegulationType }
     * 
     */
    public ProductVoltageRegulationType createProductVoltageRegulationType() {
        return new ProductVoltageRegulationType();
    }

    /**
     * Create an instance of {@link OfferCurveType }
     * 
     */
    public OfferCurveType createOfferCurveType() {
        return new OfferCurveType();
    }

    /**
     * Create an instance of {@link MaximumPowerType }
     * 
     */
    public MaximumPowerType createMaximumPowerType() {
        return new MaximumPowerType();
    }

    /**
     * Create an instance of {@link GenerationType }
     * 
     */
    public GenerationType createGenerationType() {
        return new GenerationType();
    }

    /**
     * Create an instance of {@link PercentRampRateType }
     * 
     */
    public PercentRampRateType createPercentRampRateType() {
        return new PercentRampRateType();
    }

    /**
     * Create an instance of {@link VMinType }
     * 
     */
    public VMinType createVMinType() {
        return new VMinType();
    }

    /**
     * Create an instance of {@link LoadReductionType }
     * 
     */
    public LoadReductionType createLoadReductionType() {
        return new LoadReductionType();
    }

    /**
     * Create an instance of {@link VMaxType }
     * 
     */
    public VMaxType createVMaxType() {
        return new VMaxType();
    }

    /**
     * Create an instance of {@link PMaxType }
     * 
     */
    public PMaxType createPMaxType() {
        return new PMaxType();
    }

    /**
     * Create an instance of {@link RegulationServiceType }
     * 
     */
    public RegulationServiceType createRegulationServiceType() {
        return new RegulationServiceType();
    }

    /**
     * Create an instance of {@link MinimumLoadType }
     * 
     */
    public MinimumLoadType createMinimumLoadType() {
        return new MinimumLoadType();
    }

    /**
     * Create an instance of {@link PowerRampSegmentType }
     * 
     */
    public PowerRampSegmentType createPowerRampSegmentType() {
        return new PowerRampSegmentType();
    }

    /**
     * Create an instance of {@link QMaxType }
     * 
     */
    public QMaxType createQMaxType() {
        return new QMaxType();
    }

    /**
     * Create an instance of {@link MaximumEnergyType }
     * 
     */
    public MaximumEnergyType createMaximumEnergyType() {
        return new MaximumEnergyType();
    }

    /**
     * Create an instance of {@link MinimumLoadReductionType }
     * 
     */
    public MinimumLoadReductionType createMinimumLoadReductionType() {
        return new MinimumLoadReductionType();
    }

    /**
     * Create an instance of {@link OfferSegmentType }
     * 
     */
    public OfferSegmentType createOfferSegmentType() {
        return new OfferSegmentType();
    }

    /**
     * Create an instance of {@link PowerRampType }
     * 
     */
    public PowerRampType createPowerRampType() {
        return new PowerRampType();
    }

    /**
     * Create an instance of {@link ResourceDescriptionType }
     * 
     */
    public ResourceDescriptionType createResourceDescriptionType() {
        return new ResourceDescriptionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "maximumResponse")
    public JAXBElement<Float> createMaximumResponse(Float value) {
        return new JAXBElement<Float>(_MaximumResponse_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferCurveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "offerCurve", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "baseTerm")
    public JAXBElement<OfferCurveType> createOfferCurve(OfferCurveType value) {
        return new JAXBElement<OfferCurveType>(_OfferCurve_QNAME, OfferCurveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "resourceType")
    public JAXBElement<String> createResourceType(String value) {
        return new JAXBElement<String>(_ResourceType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DurationPropType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "dispatchUp")
    public JAXBElement<DurationPropType> createDispatchUp(DurationPropType value) {
        return new JAXBElement<DurationPropType>(_DispatchUp_QNAME, DurationPropType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PMaxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "pMax")
    public JAXBElement<PMaxType> createPMax(PMaxType value) {
        return new JAXBElement<PMaxType>(_PMax_QNAME, PMaxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "endRamp")
    public JAXBElement<Integer> createEndRamp(Integer value) {
        return new JAXBElement<Integer>(_EndRamp_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DurationPropType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "dispatchTime")
    public JAXBElement<DurationPropType> createDispatchTime(DurationPropType value) {
        return new JAXBElement<DurationPropType>(_DispatchTime_QNAME, DurationPropType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferSegmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "offerSegment")
    public JAXBElement<OfferSegmentType> createOfferSegment(OfferSegmentType value) {
        return new JAXBElement<OfferSegmentType>(_OfferSegment_QNAME, OfferSegmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegulationServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "regulationService", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "productDescription")
    public JAXBElement<RegulationServiceType> createRegulationService(RegulationServiceType value) {
        return new JAXBElement<RegulationServiceType>(_RegulationService_QNAME, RegulationServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerRampSegmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "powerRampSegment")
    public JAXBElement<PowerRampSegmentType> createPowerRampSegment(PowerRampSegmentType value) {
        return new JAXBElement<PowerRampSegmentType>(_PowerRampSegment_QNAME, PowerRampSegmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRampSegments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "stagingRamp")
    public JAXBElement<ArrayOfRampSegments> createStagingRamp(ArrayOfRampSegments value) {
        return new JAXBElement<ArrayOfRampSegments>(_StagingRamp_QNAME, ArrayOfRampSegments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DurationPropType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "window")
    public JAXBElement<DurationPropType> createWindow(DurationPropType value) {
        return new JAXBElement<DurationPropType>(_Window_QNAME, DurationPropType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "maximumDeliveryRate")
    public JAXBElement<Float> createMaximumDeliveryRate(Float value) {
        return new JAXBElement<Float>(_MaximumDeliveryRate_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadReductionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "loadReduction", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "productDescription")
    public JAXBElement<LoadReductionType> createLoadReduction(LoadReductionType value) {
        return new JAXBElement<LoadReductionType>(_LoadReduction_QNAME, LoadReductionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "minimumResponse")
    public JAXBElement<Float> createMinimumResponse(Float value) {
        return new JAXBElement<Float>(_MinimumResponse_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "powerResponse")
    public JAXBElement<PowerResponseType> createPowerResponse(PowerResponseType value) {
        return new JAXBElement<PowerResponseType>(_PowerResponse_QNAME, PowerResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PercentRampRateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "percentRampRate")
    public JAXBElement<PercentRampRateType> createPercentRampRate(PercentRampRateType value) {
        return new JAXBElement<PercentRampRateType>(_PercentRampRate_QNAME, PercentRampRateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QMaxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "qMax")
    public JAXBElement<QMaxType> createQMax(QMaxType value) {
        return new JAXBElement<QMaxType>(_QMax_QNAME, QMaxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRampSegments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "recoveryRamp")
    public JAXBElement<ArrayOfRampSegments> createRecoveryRamp(ArrayOfRampSegments value) {
        return new JAXBElement<ArrayOfRampSegments>(_RecoveryRamp_QNAME, ArrayOfRampSegments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "rate")
    public JAXBElement<Float> createRate(Float value) {
        return new JAXBElement<Float>(_Rate_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRampSegments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "powerRamp")
    public JAXBElement<ArrayOfRampSegments> createPowerRamp(ArrayOfRampSegments value) {
        return new JAXBElement<ArrayOfRampSegments>(_PowerRamp_QNAME, ArrayOfRampSegments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MinimumLoadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "minimumLoad", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "baseTerm")
    public JAXBElement<MinimumLoadType> createMinimumLoad(MinimumLoadType value) {
        return new JAXBElement<MinimumLoadType>(_MinimumLoad_QNAME, MinimumLoadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "generation", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "productDescription")
    public JAXBElement<GenerationType> createGeneration(GenerationType value) {
        return new JAXBElement<GenerationType>(_Generation_QNAME, GenerationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaximumEnergyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "maximumEnergy", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "baseTerm")
    public JAXBElement<MaximumEnergyType> createMaximumEnergy(MaximumEnergyType value) {
        return new JAXBElement<MaximumEnergyType>(_MaximumEnergy_QNAME, MaximumEnergyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MinimumLoadReductionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "minimumLoadReduction", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "baseTerm")
    public JAXBElement<MinimumLoadReductionType> createMinimumLoadReduction(MinimumLoadReductionType value) {
        return new JAXBElement<MinimumLoadReductionType>(_MinimumLoadReduction_QNAME, MinimumLoadReductionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductTypeRegulationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "productTypeRegulation")
    public JAXBElement<ProductTypeRegulationType> createProductTypeRegulation(ProductTypeRegulationType value) {
        return new JAXBElement<ProductTypeRegulationType>(_ProductTypeRegulation_QNAME, ProductTypeRegulationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "targetRegulation")
    public JAXBElement<PowerAttributesType> createTargetRegulation(PowerAttributesType value) {
        return new JAXBElement<PowerAttributesType>(_TargetRegulation_QNAME, PowerAttributesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveReserveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "activeReserve", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "productDescription")
    public JAXBElement<ActiveReserveType> createActiveReserve(ActiveReserveType value) {
        return new JAXBElement<ActiveReserveType>(_ActiveReserve_QNAME, ActiveReserveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DurationPropType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "dispatchDown")
    public JAXBElement<DurationPropType> createDispatchDown(DurationPropType value) {
        return new JAXBElement<DurationPropType>(_DispatchDown_QNAME, DurationPropType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRampSegments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "rampSegments")
    public JAXBElement<ArrayOfRampSegments> createRampSegments(ArrayOfRampSegments value) {
        return new JAXBElement<ArrayOfRampSegments>(_RampSegments_QNAME, ArrayOfRampSegments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "minimumDeliveryRate")
    public JAXBElement<Float> createMinimumDeliveryRate(Float value) {
        return new JAXBElement<Float>(_MinimumDeliveryRate_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VMinType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "vMin")
    public JAXBElement<VMinType> createVMin(VMinType value) {
        return new JAXBElement<VMinType>(_VMin_QNAME, VMinType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductVoltageRegulationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "productVoltageRegulation", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "productDescription")
    public JAXBElement<ProductVoltageRegulationType> createProductVoltageRegulation(ProductVoltageRegulationType value) {
        return new JAXBElement<ProductVoltageRegulationType>(_ProductVoltageRegulation_QNAME, ProductVoltageRegulationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "beginRamp")
    public JAXBElement<Integer> createBeginRamp(Integer value) {
        return new JAXBElement<Integer>(_BeginRamp_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VMaxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "vMax")
    public JAXBElement<VMaxType> createVMax(VMaxType value) {
        return new JAXBElement<VMaxType>(_VMax_QNAME, VMaxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DurationPropType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "rampTime")
    public JAXBElement<DurationPropType> createRampTime(DurationPropType value) {
        return new JAXBElement<DurationPropType>(_RampTime_QNAME, DurationPropType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaximumPowerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power/resource", name = "maximumPower", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/emix/2011/06", substitutionHeadName = "baseTerm")
    public JAXBElement<MaximumPowerType> createMaximumPower(MaximumPowerType value) {
        return new JAXBElement<MaximumPowerType>(_MaximumPower_QNAME, MaximumPowerType.class, null, value);
    }

}
