//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ietf.params.xml.ns.icalendar_2.DurationPropType;
import org.oasis_open.docs.ns.emix._2011._06.power.PowerQuantityType;


/**
 * A Power Ramp Segment describes a change up or down in units/duration. A ramp rate holds for the duration between beginRamp to endRamp
 * 
 * <p>Java class for PowerRampSegmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowerRampSegmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rate" type="{http://docs.oasis-open.org/ns/emix/2011/06/power}PowerQuantityType"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}duration"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power/resource}beginRamp"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power/resource}endRamp"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}integralOnly"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowerRampSegmentType", propOrder = {
    "rate",
    "duration",
    "beginRamp",
    "endRamp",
    "integralOnly"
})
public class PowerRampSegmentType {

    @XmlElement(required = true)
    protected PowerQuantityType rate;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0", required = true)
    protected DurationPropType duration;
    protected int beginRamp;
    protected int endRamp;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06")
    protected boolean integralOnly;

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link PowerQuantityType }
     *     
     */
    public PowerQuantityType getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerQuantityType }
     *     
     */
    public void setRate(PowerQuantityType value) {
        this.rate = value;
    }

    public boolean isSetRate() {
        return (this.rate!= null);
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link DurationPropType }
     *     
     */
    public DurationPropType getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationPropType }
     *     
     */
    public void setDuration(DurationPropType value) {
        this.duration = value;
    }

    public boolean isSetDuration() {
        return (this.duration!= null);
    }

    /**
     * Gets the value of the beginRamp property.
     * 
     */
    public int getBeginRamp() {
        return beginRamp;
    }

    /**
     * Sets the value of the beginRamp property.
     * 
     */
    public void setBeginRamp(int value) {
        this.beginRamp = value;
    }

    public boolean isSetBeginRamp() {
        return true;
    }

    /**
     * Gets the value of the endRamp property.
     * 
     */
    public int getEndRamp() {
        return endRamp;
    }

    /**
     * Sets the value of the endRamp property.
     * 
     */
    public void setEndRamp(int value) {
        this.endRamp = value;
    }

    public boolean isSetEndRamp() {
        return true;
    }

    /**
     * Gets the value of the integralOnly property.
     * 
     */
    public boolean isIntegralOnly() {
        return integralOnly;
    }

    /**
     * Sets the value of the integralOnly property.
     * 
     */
    public void setIntegralOnly(boolean value) {
        this.integralOnly = value;
    }

    public boolean isSetIntegralOnly() {
        return true;
    }

}
