//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power.resource;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.ArrayOfTerms;
import org.oasis_open.docs.ns.emix._2011._06.EmixInterfaceType;
import org.oasis_open.docs.ns.emix._2011._06.ProductDescriptionType;
import org.oasis_open.docs.ns.emix._2011._06.ServiceAreaType;
import org.oasis_open.docs.ns.emix._2011._06.power.AggregatedPnodeType;
import org.oasis_open.docs.ns.emix._2011._06.power.EndDeviceAssetType;
import org.oasis_open.docs.ns.emix._2011._06.power.MeterAssetType;
import org.oasis_open.docs.ns.emix._2011._06.power.PnodeType;
import org.oasis_open.docs.ns.emix._2011._06.power.ServiceDeliveryPointType;
import org.oasis_open.docs.ns.emix._2011._06.power.ServiceLocationType;
import org.oasis_open.docs.ns.emix._2011._06.power.TransportInterfaceType;


/**
 * Resource Description based on the EMIX Product Description.
 * 
 * <p>Java class for ResourceDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceDescriptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/emix/2011/06}ProductDescriptionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}mrid"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}emixInterface"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}terms" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceDescriptionType", propOrder = {
    "mrid",
    "emixInterface",
    "terms"
})
@XmlSeeAlso({
    ActiveReserveType.class,
    ProductVoltageRegulationType.class,
    PowerResponseType.class,
    RegulationServiceType.class
})
public class ResourceDescriptionType
    extends ProductDescriptionType
{

    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power", required = true)
    protected String mrid;
    @XmlElementRef(name = "emixInterface", namespace = "http://docs.oasis-open.org/ns/emix/2011/06", type = JAXBElement.class)
    protected JAXBElement<? extends EmixInterfaceType> emixInterface;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06")
    protected ArrayOfTerms terms;

    /**
     * Gets the value of the mrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrid() {
        return mrid;
    }

    /**
     * Sets the value of the mrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrid(String value) {
        this.mrid = value;
    }

    public boolean isSetMrid() {
        return (this.mrid!= null);
    }

    /**
     * Gets the value of the emixInterface property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EmixInterfaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceLocationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceDeliveryPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PnodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TransportInterfaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link EndDeviceAssetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MeterAssetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AggregatedPnodeType }{@code >}
     *     
     */
    public JAXBElement<? extends EmixInterfaceType> getEmixInterface() {
        return emixInterface;
    }

    /**
     * Sets the value of the emixInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EmixInterfaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceLocationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceDeliveryPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PnodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TransportInterfaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link EndDeviceAssetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MeterAssetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AggregatedPnodeType }{@code >}
     *     
     */
    public void setEmixInterface(JAXBElement<? extends EmixInterfaceType> value) {
        this.emixInterface = value;
    }

    public boolean isSetEmixInterface() {
        return (this.emixInterface!= null);
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTerms }
     *     
     */
    public ArrayOfTerms getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTerms }
     *     
     */
    public void setTerms(ArrayOfTerms value) {
        this.terms = value;
    }

    public boolean isSetTerms() {
        return (this.terms!= null);
    }

}
