//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Collection of Emix Power Transport Product Charges
 * 
 * <p>Java class for ArrayOfTransportCharges complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfTransportCharges">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}baseTransportCharge" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfTransportCharges", propOrder = {
    "baseTransportCharge"
})
public class ArrayOfTransportCharges {

    @XmlElementRef(name = "baseTransportCharge", namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends BaseTransportChargeType>> baseTransportCharge;

    /**
     * Gets the value of the baseTransportCharge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseTransportCharge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseTransportCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link CongestionChargeType }{@code >}
     * {@link JAXBElement }{@code <}{@link BaseTransportChargeType }{@code >}
     * {@link JAXBElement }{@code <}{@link MarginalLossType }{@code >}
     * {@link JAXBElement }{@code <}{@link CongestionRevenueRightsType }{@code >}
     * {@link JAXBElement }{@code <}{@link MarginalLossChargeType }{@code >}
     * {@link JAXBElement }{@code <}{@link ConversionLossType }{@code >}
     * {@link JAXBElement }{@code <}{@link TransportAccessFeeType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends BaseTransportChargeType>> getBaseTransportCharge() {
        if (baseTransportCharge == null) {
            baseTransportCharge = new ArrayList<JAXBElement<? extends BaseTransportChargeType>>();
        }
        return this.baseTransportCharge;
    }

    public boolean isSetBaseTransportCharge() {
        return ((this.baseTransportCharge!= null)&&(!this.baseTransportCharge.isEmpty()));
    }

    public void unsetBaseTransportCharge() {
        this.baseTransportCharge = null;
    }

}
