//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * An identification of the standard or other protocol used to measure power quality. Sets definition for all other power attributes. Type of Abstract extension object  for Power Qualities
 * 
 * <p>Java class for BasePowerQualityIndicatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasePowerQualityIndicatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasePowerQualityIndicatorType")
@XmlSeeAlso({
    TemporaryOvervoltageType.class,
    SupplyVoltageDipsType.class,
    HarmonicVoltageType.class,
    FlickerLtType.class,
    LongInterruptionsType.class,
    MainsSignallingVoltageType.class,
    SupplyVoltageVariationsType.class,
    MainsVoltageType.class,
    RapidVoltageChangesType.class,
    ShortInterruptionsType.class,
    SupplyVoltageImbalanceType.class,
    PowerFrequencyType.class,
    FlickerStType.class
})
public abstract class BasePowerQualityIndicatorType {


}
