//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasurementProtocolEnumeratedType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MeasurementProtocolEnumeratedType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EN 50160"/>
 *     &lt;enumeration value="IEEE 1549-2009"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MeasurementProtocolEnumeratedType")
@XmlEnum
public enum MeasurementProtocolEnumeratedType {

    @XmlEnumValue("EN 50160")
    EN_50160("EN 50160"),
    @XmlEnumValue("IEEE 1549-2009")
    IEEE_1549_2009("IEEE 1549-2009");
    private final String value;

    MeasurementProtocolEnumeratedType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MeasurementProtocolEnumeratedType fromValue(String v) {
        for (MeasurementProtocolEnumeratedType c: MeasurementProtocolEnumeratedType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
