//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.EmixInterfaceType;
import org.oasis_open.docs.ns.emix._2011._06.ProductDescriptionType;
import org.oasis_open.docs.ns.emix._2011._06.ServiceAreaType;


/**
 * Product Description for simple power transactions, also used as template for other Power Product Description Types. The product is constant power, which dictates the rate of delivery. After a specified duration, energy has been delivered, price per unit of energy.
 * 
 * <p>Java class for PowerProductDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowerProductDescriptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/emix/2011/06}ProductDescriptionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}productType"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}emixInterface"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}unitEnergyPrice" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}powerItem" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}charges" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowerProductDescriptionType", propOrder = {
    "productType",
    "emixInterface",
    "unitEnergyPrice",
    "powerItem",
    "charges"
})
@XmlSeeAlso({
    TransportProductDescriptionType.class,
    BlockPowerFullRequirementsType.class,
    FullRequirementsPowerType.class
})
public class PowerProductDescriptionType
    extends ProductDescriptionType
{

    @XmlElement(required = true)
    protected String productType;
    @XmlElementRef(name = "emixInterface", namespace = "http://docs.oasis-open.org/ns/emix/2011/06", type = JAXBElement.class)
    protected JAXBElement<? extends EmixInterfaceType> emixInterface;
    protected UnitEnergyPriceType unitEnergyPrice;
    @XmlElementRef(name = "powerItem", namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends PowerItemType> powerItem;
    protected ArrayOfCharges charges;

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    public boolean isSetProductType() {
        return (this.productType!= null);
    }

    /**
     * Gets the value of the emixInterface property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EmixInterfaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceLocationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceDeliveryPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PnodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TransportInterfaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link EndDeviceAssetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MeterAssetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AggregatedPnodeType }{@code >}
     *     
     */
    public JAXBElement<? extends EmixInterfaceType> getEmixInterface() {
        return emixInterface;
    }

    /**
     * Sets the value of the emixInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EmixInterfaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceLocationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceDeliveryPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PnodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ServiceAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TransportInterfaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link EndDeviceAssetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MeterAssetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AggregatedPnodeType }{@code >}
     *     
     */
    public void setEmixInterface(JAXBElement<? extends EmixInterfaceType> value) {
        this.emixInterface = value;
    }

    public boolean isSetEmixInterface() {
        return (this.emixInterface!= null);
    }

    /**
     * Gets the value of the unitEnergyPrice property.
     * 
     * @return
     *     possible object is
     *     {@link UnitEnergyPriceType }
     *     
     */
    public UnitEnergyPriceType getUnitEnergyPrice() {
        return unitEnergyPrice;
    }

    /**
     * Sets the value of the unitEnergyPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitEnergyPriceType }
     *     
     */
    public void setUnitEnergyPrice(UnitEnergyPriceType value) {
        this.unitEnergyPrice = value;
    }

    public boolean isSetUnitEnergyPrice() {
        return (this.unitEnergyPrice!= null);
    }

    /**
     * Gets the value of the powerItem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PowerItemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PowerApparentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PowerReactiveType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PowerRealType }{@code >}
     *     
     */
    public JAXBElement<? extends PowerItemType> getPowerItem() {
        return powerItem;
    }

    /**
     * Sets the value of the powerItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PowerItemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PowerApparentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PowerReactiveType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PowerRealType }{@code >}
     *     
     */
    public void setPowerItem(JAXBElement<? extends PowerItemType> value) {
        this.powerItem = value;
    }

    public boolean isSetPowerItem() {
        return (this.powerItem!= null);
    }

    /**
     * Gets the value of the charges property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCharges }
     *     
     */
    public ArrayOfCharges getCharges() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCharges }
     *     
     */
    public void setCharges(ArrayOfCharges value) {
        this.charges = value;
    }

    public boolean isSetCharges() {
        return (this.charges!= null);
    }

}
