//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.QualityWarrantType;
import org.oasis_open.docs.ns.emix._2011._06.SideType;


/**
 * A Power Quality Warrant asserts or requires that the power be of a certain quality or better. This type extends the EMIX Quality Warrant for use in describing power. The Power Quality Warrant is a collection of the most commonly used Quality Measurements. Users who require a Quality Measure not on this list can extend the Quality Measure Type to create new Quality Measures. Note: Quality Measure can be applied EITHER in the intervals of the schedule in emixBase inherited from the emix:QualityWarrant OR in external to the Intervals, but not both..
 * 
 * <p>Java class for PowerQualityWarrantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowerQualityWarrantType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/emix/2011/06}QualityWarrantType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}uid"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}measurementProtocol"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}qualityType"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}side"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}qualityMeasure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowerQualityWarrantType", propOrder = {
    "uid",
    "measurementProtocol",
    "qualityType",
    "side",
    "qualityMeasure"
})
public class PowerQualityWarrantType
    extends QualityWarrantType
{

    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06", required = true)
    protected String uid;
    @XmlElement(required = true)
    protected String measurementProtocol;
    @XmlElement(required = true)
    protected String qualityType;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06", required = true)
    protected SideType side;
    protected QualityMeasureType qualityMeasure;

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    public boolean isSetUid() {
        return (this.uid!= null);
    }

    /**
     * Gets the value of the measurementProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementProtocol() {
        return measurementProtocol;
    }

    /**
     * Sets the value of the measurementProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementProtocol(String value) {
        this.measurementProtocol = value;
    }

    public boolean isSetMeasurementProtocol() {
        return (this.measurementProtocol!= null);
    }

    /**
     * Gets the value of the qualityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualityType() {
        return qualityType;
    }

    /**
     * Sets the value of the qualityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualityType(String value) {
        this.qualityType = value;
    }

    public boolean isSetQualityType() {
        return (this.qualityType!= null);
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link SideType }
     *     
     */
    public SideType getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideType }
     *     
     */
    public void setSide(SideType value) {
        this.side = value;
    }

    public boolean isSetSide() {
        return (this.side!= null);
    }

    /**
     * Gets the value of the qualityMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link QualityMeasureType }
     *     
     */
    public QualityMeasureType getQualityMeasure() {
        return qualityMeasure;
    }

    /**
     * Sets the value of the qualityMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityMeasureType }
     *     
     */
    public void setQualityMeasure(QualityMeasureType value) {
        this.qualityMeasure = value;
    }

    public boolean isSetQualityMeasure() {
        return (this.qualityMeasure!= null);
    }

}
