//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.ItemBaseType;
import org.oasis_open.docs.ns.emix._2011._06.siscale.SiScaleCodeType;


/**
 * Base for the measurement of Power
 * 
 * <p>Java class for PowerItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowerItemType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/emix/2011/06}ItemBaseType">
 *       &lt;sequence>
 *         &lt;element name="itemDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itemUnits" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/siscale}siScaleCode"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}powerAttributes"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowerItemType", propOrder = {
    "itemDescription",
    "itemUnits",
    "siScaleCode",
    "powerAttributes"
})
@XmlSeeAlso({
    PowerApparentType.class,
    PowerReactiveType.class,
    PowerRealType.class
})
public abstract class PowerItemType
    extends ItemBaseType
{

    @XmlElement(required = true)
    protected String itemDescription;
    @XmlElement(required = true)
    protected String itemUnits;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06/siscale", required = true)
    protected SiScaleCodeType siScaleCode;
    @XmlElement(required = true)
    protected PowerAttributesType powerAttributes;

    /**
     * Gets the value of the itemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDescription() {
        return itemDescription;
    }

    /**
     * Sets the value of the itemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDescription(String value) {
        this.itemDescription = value;
    }

    public boolean isSetItemDescription() {
        return (this.itemDescription!= null);
    }

    /**
     * Gets the value of the itemUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemUnits() {
        return itemUnits;
    }

    /**
     * Sets the value of the itemUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemUnits(String value) {
        this.itemUnits = value;
    }

    public boolean isSetItemUnits() {
        return (this.itemUnits!= null);
    }

    /**
     * Gets the value of the siScaleCode property.
     * 
     * @return
     *     possible object is
     *     {@link SiScaleCodeType }
     *     
     */
    public SiScaleCodeType getSiScaleCode() {
        return siScaleCode;
    }

    /**
     * Sets the value of the siScaleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiScaleCodeType }
     *     
     */
    public void setSiScaleCode(SiScaleCodeType value) {
        this.siScaleCode = value;
    }

    public boolean isSetSiScaleCode() {
        return (this.siScaleCode!= null);
    }

    /**
     * Gets the value of the powerAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link PowerAttributesType }
     *     
     */
    public PowerAttributesType getPowerAttributes() {
        return powerAttributes;
    }

    /**
     * Sets the value of the powerAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerAttributesType }
     *     
     */
    public void setPowerAttributes(PowerAttributesType value) {
        this.powerAttributes = value;
    }

    public boolean isSetPowerAttributes() {
        return (this.powerAttributes!= null);
    }

}
