//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductTypeEnumeratedType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProductTypeEnumeratedType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="energy"/>
 *     &lt;enumeration value="transport"/>
 *     &lt;enumeration value="energyOption"/>
 *     &lt;enumeration value="transportOption"/>
 *     &lt;enumeration value="fullRequirementsPower"/>
 *     &lt;enumeration value="fullRequirementsPowerBlockPricing"/>
 *     &lt;enumeration value="fullRequirementsPowerWithDemandCharge"/>
 *     &lt;enumeration value="fullRequirementsPowerWithMaximumAndMinimum"/>
 *     &lt;enumeration value="hourlyDayAhead"/>
 *     &lt;enumeration value="exAnteRealTimePrice"/>
 *     &lt;enumeration value="timeOfUsePricing"/>
 *     &lt;enumeration value="congestionRevenueRights"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProductTypeEnumeratedType")
@XmlEnum
public enum ProductTypeEnumeratedType {

    @XmlEnumValue("energy")
    ENERGY("energy"),
    @XmlEnumValue("transport")
    TRANSPORT("transport"),
    @XmlEnumValue("energyOption")
    ENERGY_OPTION("energyOption"),
    @XmlEnumValue("transportOption")
    TRANSPORT_OPTION("transportOption"),
    @XmlEnumValue("fullRequirementsPower")
    FULL_REQUIREMENTS_POWER("fullRequirementsPower"),
    @XmlEnumValue("fullRequirementsPowerBlockPricing")
    FULL_REQUIREMENTS_POWER_BLOCK_PRICING("fullRequirementsPowerBlockPricing"),
    @XmlEnumValue("fullRequirementsPowerWithDemandCharge")
    FULL_REQUIREMENTS_POWER_WITH_DEMAND_CHARGE("fullRequirementsPowerWithDemandCharge"),
    @XmlEnumValue("fullRequirementsPowerWithMaximumAndMinimum")
    FULL_REQUIREMENTS_POWER_WITH_MAXIMUM_AND_MINIMUM("fullRequirementsPowerWithMaximumAndMinimum"),
    @XmlEnumValue("hourlyDayAhead")
    HOURLY_DAY_AHEAD("hourlyDayAhead"),
    @XmlEnumValue("exAnteRealTimePrice")
    EX_ANTE_REAL_TIME_PRICE("exAnteRealTimePrice"),
    @XmlEnumValue("timeOfUsePricing")
    TIME_OF_USE_PRICING("timeOfUsePricing"),
    @XmlEnumValue("congestionRevenueRights")
    CONGESTION_REVENUE_RIGHTS("congestionRevenueRights");
    private final String value;

    ProductTypeEnumeratedType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProductTypeEnumeratedType fromValue(String v) {
        for (ProductTypeEnumeratedType c: ProductTypeEnumeratedType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
