//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.PriceType;


/**
 * Product Description for charges and revenue related to Transport Services for a Power Product, i.e., the movement of Power through Transmission and Distribution. The Interface used matches a segment of the transport infrastructure, usually identified by an injection node and a delivery node.
 * 
 * <p>Java class for TransportProductDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportProductDescriptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/emix/2011/06/power}PowerProductDescriptionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}price"/>
 *         &lt;element name="transportCharges" type="{http://docs.oasis-open.org/ns/emix/2011/06/power}ArrayOfTransportCharges"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportProductDescriptionType", propOrder = {
    "price",
    "transportCharges"
})
public class TransportProductDescriptionType
    extends PowerProductDescriptionType
{

    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06", required = true)
    protected PriceType price;
    @XmlElement(required = true)
    protected ArrayOfTransportCharges transportCharges;

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    public boolean isSetPrice() {
        return (this.price!= null);
    }

    /**
     * Gets the value of the transportCharges property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTransportCharges }
     *     
     */
    public ArrayOfTransportCharges getTransportCharges() {
        return transportCharges;
    }

    /**
     * Sets the value of the transportCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTransportCharges }
     *     
     */
    public void setTransportCharges(ArrayOfTransportCharges value) {
        this.transportCharges = value;
    }

    public boolean isSetTransportCharges() {
        return (this.transportCharges!= null);
    }

}
