//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06.power;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.PriceType;


/**
 * Transport Access Fee is a Fixed Charge (not dependent on congestion or quantity) to access a transport system.
 * 
 * <p>Java class for TransportAccessFeeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportAccessFeeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/emix/2011/06/power}BaseTransportChargeType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06/power}transportInterface"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}price"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportAccessFeeType", propOrder = {
    "transportInterface",
    "price"
})
public class TransportAccessFeeType
    extends BaseTransportChargeType
{

    @XmlElement(required = true)
    protected TransportInterfaceType transportInterface;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06", required = true)
    protected PriceType price;

    /**
     * Gets the value of the transportInterface property.
     * 
     * @return
     *     possible object is
     *     {@link TransportInterfaceType }
     *     
     */
    public TransportInterfaceType getTransportInterface() {
        return transportInterface;
    }

    /**
     * Sets the value of the transportInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportInterfaceType }
     *     
     */
    public void setTransportInterface(TransportInterfaceType value) {
        this.transportInterface = value;
    }

    public boolean isSetTransportInterface() {
        return (this.transportInterface!= null);
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    public boolean isSetPrice() {
        return (this.price!= null);
    }

}
