//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 09:48:32 AM PDT 
//


package com.cleanspark.cs.wrapper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.oasis_open.docs.ns.energyinterop._201110.EiTenderType;

import EiTender.EiCreateTenderType;
import EiTender.EiCreatedTenderType;
import EiTender.EiDistributeTenderType;
import EiTransaction.EiCreateTransactionType;
import EiTransaction.EiCreatedTransactionType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createTenderType",
	"createdTenderType",
	"distributeTenderType",
	"createTransactionType",
	"createdTransactionType"
})
@XmlRootElement(name = "oadrSignedObject")
public class TeSignedObject {

    protected EiCreateTenderType createTenderType;
    protected EiCreatedTenderType createdTenderType;
    protected EiDistributeTenderType distributeTenderType;
    protected EiCreateTransactionType createTransactionType;
    protected EiCreatedTransactionType createdTransactionType;
 

	@XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    public EiCreateTenderType getEiCreateTenderType() {
        return createTenderType;
    }
    
    public void setEiCreateTenderType(EiCreateTenderType createTender) {
        this.createTenderType = createTender;
    }
    
    public EiCreatedTenderType getEiCreatedTenderType() {
        return createdTenderType;
    }

    public void setEiCreatedTenderType(EiCreatedTenderType createdTender) {
        this.createdTenderType = createdTender;
    }
    
    public EiDistributeTenderType getDistributeTenderType() {
 		return distributeTenderType;
 	}

 	public void setDistributeTenderType(EiDistributeTenderType distributeTenderType) {
 		this.distributeTenderType = distributeTenderType;
 	}
 	
 	public EiCreateTransactionType getCreateTransactionType() {
		return createTransactionType;
	}

	public void setCreateTransactionType(EiCreateTransactionType createTransactionType) {
		this.createTransactionType = createTransactionType;
	}
	
	public EiCreatedTransactionType getCreatedTransactionType() {
		return createdTransactionType;
	}

	public void setCreatedTransactionType(EiCreatedTransactionType createdTransactionType) {
		this.createdTransactionType = createdTransactionType;
	}


    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
