//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Collection of Event Responses. When an regards multiple referenceable items, each referenced item MAY have its own response. Always accompanied by an overall Response Type. 
 * 
 * <p>Java class for ArrayofEventResponses complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayofEventResponses">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventResponse" type="{http://docs.oasis-open.org/ns/energyinterop/201110}EiEventResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayofEventResponses", propOrder = {
    "eventResponse"
})
public class ArrayofEventResponses {

    protected List<EiEventResponseType> eventResponse;

    /**
     * Gets the value of the eventResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EiEventResponseType }
     * 
     * 
     */
    public List<EiEventResponseType> getEventResponse() {
        if (eventResponse == null) {
            eventResponse = new ArrayList<EiEventResponseType>();
        }
        return this.eventResponse;
    }

    public boolean isSetEventResponse() {
        return ((this.eventResponse!= null)&&(!this.eventResponse.isEmpty()));
    }

    public void unsetEventResponse() {
        this.eventResponse = null;
    }

}
