//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Current Value reprises what the Signal Payload is at the moment EventInfo is created.
 * 
 * <p>Java class for CurrentValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CurrentValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}payloadBase"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrentValueType", propOrder = {
    "payloadBase"
})
public class CurrentValueType {

    @XmlElementRef(name = "payloadBase", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110", type = JAXBElement.class)
    protected JAXBElement<? extends PayloadBaseType> payloadBase;

    /**
     * Gets the value of the payloadBase property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PayloadPriceMultiplierType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadPriceRelativeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadBaseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadPriceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadApplicationSpecificType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadProductType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadQuantityType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadLevelType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadFloatType }{@code >}
     *     
     */
    public JAXBElement<? extends PayloadBaseType> getPayloadBase() {
        return payloadBase;
    }

    /**
     * Sets the value of the payloadBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PayloadPriceMultiplierType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadPriceRelativeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadBaseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadPriceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadApplicationSpecificType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadProductType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadQuantityType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadLevelType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadFloatType }{@code >}
     *     
     */
    public void setPayloadBase(JAXBElement<? extends PayloadBaseType> value) {
        this.payloadBase = value;
    }

    public boolean isSetPayloadBase() {
        return (this.payloadBase!= null);
    }

}
