//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EiAvailBehaviorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EiAvailBehaviorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="accept"/>
 *     &lt;enumeration value="reject"/>
 *     &lt;enumeration value="restrict"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EiAvailBehaviorType")
@XmlEnum
public enum EiAvailBehaviorType {


    /**
     * Simply accept the issued DR event regardless of any conflicts
     * 
     */
    @XmlEnumValue("accept")
    ACCEPT("accept"),

    /**
     * Reject any DR events that conflict with configured constraints
     * 
     */
    @XmlEnumValue("reject")
    REJECT("reject"),

    /**
     * Modify the DR event parameters so that they legally fall within the bounds of the configured parameters.
     * 
     */
    @XmlEnumValue("restrict")
    RESTRICT("restrict");
    private final String value;

    EiAvailBehaviorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EiAvailBehaviorType fromValue(String v) {
        for (EiAvailBehaviorType c: EiAvailBehaviorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
