//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ietf.params.xml.ns.icalendar_2.VavailabilityType;


/**
 * <p>Java class for EiAvailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EiAvailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}availID"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}venID" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}resourceID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="available" type="{urn:ietf:params:xml:ns:icalendar-2.0}VavailabilityType"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}createdDateTime"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiAvailBehavior"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}marketContext"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://docs.oasis-open.org/ns/energyinterop/201110}schemaVersion"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EiAvailType", propOrder = {
    "availID",
    "venID",
    "resourceID",
    "available",
    "createdDateTime",
    "eiAvailBehavior",
    "marketContext"
})
public class EiAvailType {

    @XmlElement(required = true)
    protected String availID;
    @XmlElement(required = true)
    protected List<String> venID;
    protected List<String> resourceID;
    @XmlElement(required = true)
    protected VavailabilityType available;
    @XmlElement(required = true)
    protected XMLGregorianCalendar createdDateTime;
    @XmlElement(required = true)
    protected EiAvailBehaviorType eiAvailBehavior;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06", required = true)
    protected String marketContext;
    @XmlAttribute(name = "schemaVersion", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
    protected String schemaVersion;

    /**
     * ID for this artifact
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailID() {
        return availID;
    }

    /**
     * Sets the value of the availID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailID(String value) {
        this.availID = value;
    }

    public boolean isSetAvailID() {
        return (this.availID!= null);
    }

    /**
     * VEN that offers this availability Gets the value of the venID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the venID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVenID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVenID() {
        if (venID == null) {
            venID = new ArrayList<String>();
        }
        return this.venID;
    }

    public boolean isSetVenID() {
        return ((this.venID!= null)&&(!this.venID.isEmpty()));
    }

    public void unsetVenID() {
        this.venID = null;
    }

    /**
     * Resources to which the Availability applies.Gets the value of the resourceID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getResourceID() {
        if (resourceID == null) {
            resourceID = new ArrayList<String>();
        }
        return this.resourceID;
    }

    public boolean isSetResourceID() {
        return ((this.resourceID!= null)&&(!this.resourceID.isEmpty()));
    }

    public void unsetResourceID() {
        this.resourceID = null;
    }

    /**
     * Gets the value of the available property.
     * 
     * @return
     *     possible object is
     *     {@link VavailabilityType }
     *     
     */
    public VavailabilityType getAvailable() {
        return available;
    }

    /**
     * Sets the value of the available property.
     * 
     * @param value
     *     allowed object is
     *     {@link VavailabilityType }
     *     
     */
    public void setAvailable(VavailabilityType value) {
        this.available = value;
    }

    public boolean isSetAvailable() {
        return (this.available!= null);
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDateTime(XMLGregorianCalendar value) {
        this.createdDateTime = value;
    }

    public boolean isSetCreatedDateTime() {
        return (this.createdDateTime!= null);
    }

    /**
     * Gets the value of the eiAvailBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link EiAvailBehaviorType }
     *     
     */
    public EiAvailBehaviorType getEiAvailBehavior() {
        return eiAvailBehavior;
    }

    /**
     * Sets the value of the eiAvailBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link EiAvailBehaviorType }
     *     
     */
    public void setEiAvailBehavior(EiAvailBehaviorType value) {
        this.eiAvailBehavior = value;
    }

    public boolean isSetEiAvailBehavior() {
        return (this.eiAvailBehavior!= null);
    }

    /**
     * Gets the value of the marketContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketContext() {
        return marketContext;
    }

    /**
     * Sets the value of the marketContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketContext(String value) {
        this.marketContext = value;
    }

    public boolean isSetMarketContext() {
        return (this.marketContext!= null);
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    public boolean isSetSchemaVersion() {
        return (this.schemaVersion!= null);
    }

}
