//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ietf.params.xml.ns.icalendar_2.DurationPropType;
import org.oasis_open.docs.ns.emix._2011._06.NonStandardTermsHandlingType;


/**
 * Market Expectations inform the VEN what the expectations and rules are for a given Market Context
 * 
 * <p>Java class for EiMarketExpectationsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EiMarketExpectationsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiMarketRuleSet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}granularity" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}nonStandardTermsHandling"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EiMarketExpectationsType", propOrder = {
    "eiMarketRuleSet",
    "granularity",
    "nonStandardTermsHandling"
})
public class EiMarketExpectationsType {

    protected List<EiMarketRuleSetType> eiMarketRuleSet;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0")
    protected DurationPropType granularity;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06", required = true)
    protected NonStandardTermsHandlingType nonStandardTermsHandling;

    /**
     * Gets the value of the eiMarketRuleSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eiMarketRuleSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEiMarketRuleSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EiMarketRuleSetType }
     * 
     * 
     */
    public List<EiMarketRuleSetType> getEiMarketRuleSet() {
        if (eiMarketRuleSet == null) {
            eiMarketRuleSet = new ArrayList<EiMarketRuleSetType>();
        }
        return this.eiMarketRuleSet;
    }

    public boolean isSetEiMarketRuleSet() {
        return ((this.eiMarketRuleSet!= null)&&(!this.eiMarketRuleSet.isEmpty()));
    }

    public void unsetEiMarketRuleSet() {
        this.eiMarketRuleSet = null;
    }

    /**
     * Temporal granularity of market, i.e., a 5 minute market operates in 5 minute chunks, with a fixed offset from the beginning of the business schedule
     * 
     * @return
     *     possible object is
     *     {@link DurationPropType }
     *     
     */
    public DurationPropType getGranularity() {
        return granularity;
    }

    /**
     * Sets the value of the granularity property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationPropType }
     *     
     */
    public void setGranularity(DurationPropType value) {
        this.granularity = value;
    }

    public boolean isSetGranularity() {
        return (this.granularity!= null);
    }

    /**
     * Non-Standard terms handling defines what Parties should do with any Term not listed in the Market Rule Sets.
     * 
     * @return
     *     possible object is
     *     {@link NonStandardTermsHandlingType }
     *     
     */
    public NonStandardTermsHandlingType getNonStandardTermsHandling() {
        return nonStandardTermsHandling;
    }

    /**
     * Sets the value of the nonStandardTermsHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonStandardTermsHandlingType }
     *     
     */
    public void setNonStandardTermsHandling(NonStandardTermsHandlingType value) {
        this.nonStandardTermsHandling = value;
    }

    public boolean isSetNonStandardTermsHandling() {
        return (this.nonStandardTermsHandling!= null);
    }

}
