//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.StandardTermsSetType;


/**
 * A collection of Requirements (Constraints) and how they are processed within this market
 * 
 * <p>Java class for EiMarketRuleSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EiMarketRuleSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}standardTermsSet"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}ruleSetPurpose"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiAvailBehavior" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EiMarketRuleSetType", propOrder = {
    "standardTermsSet",
    "ruleSetPurpose",
    "eiAvailBehavior"
})
public class EiMarketRuleSetType {

    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06", required = true)
    protected StandardTermsSetType standardTermsSet;
    @XmlElement(required = true)
    protected RuleSetPurposeType ruleSetPurpose;
    protected EiAvailBehaviorType eiAvailBehavior;

    /**
     * Gets the value of the standardTermsSet property.
     * 
     * @return
     *     possible object is
     *     {@link StandardTermsSetType }
     *     
     */
    public StandardTermsSetType getStandardTermsSet() {
        return standardTermsSet;
    }

    /**
     * Sets the value of the standardTermsSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardTermsSetType }
     *     
     */
    public void setStandardTermsSet(StandardTermsSetType value) {
        this.standardTermsSet = value;
    }

    public boolean isSetStandardTermsSet() {
        return (this.standardTermsSet!= null);
    }

    /**
     * Gets the value of the ruleSetPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link RuleSetPurposeType }
     *     
     */
    public RuleSetPurposeType getRuleSetPurpose() {
        return ruleSetPurpose;
    }

    /**
     * Sets the value of the ruleSetPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleSetPurposeType }
     *     
     */
    public void setRuleSetPurpose(RuleSetPurposeType value) {
        this.ruleSetPurpose = value;
    }

    public boolean isSetRuleSetPurpose() {
        return (this.ruleSetPurpose!= null);
    }

    /**
     * Gets the value of the eiAvailBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link EiAvailBehaviorType }
     *     
     */
    public EiAvailBehaviorType getEiAvailBehavior() {
        return eiAvailBehavior;
    }

    /**
     * Sets the value of the eiAvailBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link EiAvailBehaviorType }
     *     
     */
    public void setEiAvailBehavior(EiAvailBehaviorType value) {
        this.eiAvailBehavior = value;
    }

    public boolean isSetEiAvailBehavior() {
        return (this.eiAvailBehavior!= null);
    }

}
