//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ietf.params.xml.ns.icalendar_2.VavailabilityType;


/**
 * Opts are used tby the VEN to make temporary over-rides to the pre-existing agreement. For example, a VEN may Opt In to events during the evening, or Opt Out from events during the World Series.
 * 
 * <p>Java class for EiOptType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EiOptType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}optID"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}optType"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}optReason"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}marketContext" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}venID" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}vavailability" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiMarketRuleSet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}createdDateTime"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://docs.oasis-open.org/ns/energyinterop/201110}schemaVersion"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EiOptType", propOrder = {
    "optID",
    "optType",
    "optReason",
    "marketContext",
    "venID",
    "vavailability",
    "eiMarketRuleSet",
    "createdDateTime"
})
public class EiOptType {

    @XmlElement(required = true)
    protected String optID;
    @XmlElement(required = true)
    protected OptTypeType optType;
    @XmlElement(required = true)
    protected String optReason;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06")
    protected String marketContext;
    @XmlElement(required = true)
    protected List<String> venID;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0")
    protected VavailabilityType vavailability;
    protected List<EiMarketRuleSetType> eiMarketRuleSet;
    @XmlElement(required = true)
    protected XMLGregorianCalendar createdDateTime;
    @XmlAttribute(name = "schemaVersion", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
    protected String schemaVersion;

    /**
     * This is the identifier that may used by other entities to refer to this instance of an OptOut.
     * 				
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptID() {
        return optID;
    }

    /**
     * Sets the value of the optID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptID(String value) {
        this.optID = value;
    }

    public boolean isSetOptID() {
        return (this.optID!= null);
    }

    /**
     * Gets the value of the optType property.
     * 
     * @return
     *     possible object is
     *     {@link OptTypeType }
     *     
     */
    public OptTypeType getOptType() {
        return optType;
    }

    /**
     * Sets the value of the optType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptTypeType }
     *     
     */
    public void setOptType(OptTypeType value) {
        this.optType = value;
    }

    public boolean isSetOptType() {
        return (this.optType!= null);
    }

    /**
     * Gets the value of the optReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptReason() {
        return optReason;
    }

    /**
     * Sets the value of the optReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptReason(String value) {
        this.optReason = value;
    }

    public boolean isSetOptReason() {
        return (this.optReason!= null);
    }

    /**
     * Gets the value of the marketContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketContext() {
        return marketContext;
    }

    /**
     * Sets the value of the marketContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketContext(String value) {
        this.marketContext = value;
    }

    public boolean isSetMarketContext() {
        return (this.marketContext!= null);
    }

    /**
     * Gets the value of the venID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the venID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVenID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVenID() {
        if (venID == null) {
            venID = new ArrayList<String>();
        }
        return this.venID;
    }

    public boolean isSetVenID() {
        return ((this.venID!= null)&&(!this.venID.isEmpty()));
    }

    public void unsetVenID() {
        this.venID = null;
    }

    /**
     * Gets the value of the vavailability property.
     * 
     * @return
     *     possible object is
     *     {@link VavailabilityType }
     *     
     */
    public VavailabilityType getVavailability() {
        return vavailability;
    }

    /**
     * Sets the value of the vavailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link VavailabilityType }
     *     
     */
    public void setVavailability(VavailabilityType value) {
        this.vavailability = value;
    }

    public boolean isSetVavailability() {
        return (this.vavailability!= null);
    }

    /**
     * Gets the value of the eiMarketRuleSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eiMarketRuleSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEiMarketRuleSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EiMarketRuleSetType }
     * 
     * 
     */
    public List<EiMarketRuleSetType> getEiMarketRuleSet() {
        if (eiMarketRuleSet == null) {
            eiMarketRuleSet = new ArrayList<EiMarketRuleSetType>();
        }
        return this.eiMarketRuleSet;
    }

    public boolean isSetEiMarketRuleSet() {
        return ((this.eiMarketRuleSet!= null)&&(!this.eiMarketRuleSet.isEmpty()));
    }

    public void unsetEiMarketRuleSet() {
        this.eiMarketRuleSet = null;
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDateTime(XMLGregorianCalendar value) {
        this.createdDateTime = value;
    }

    public boolean isSetCreatedDateTime() {
        return (this.createdDateTime!= null);
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    public boolean isSetSchemaVersion() {
        return (this.schemaVersion!= null);
    }

}
