//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Registration varies from Market to Market and VEN to VEN and so cannot be defined here. Perties wishing to exchange Registration should extend this abstract type to meet their particular needs.
 * 
 * <p>Java class for EiRegistrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EiRegistrationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}registreePartyID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}registrarPartyID"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eiRegistrationInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EiRegistrationType", propOrder = {
    "registreePartyID",
    "registrarPartyID",
    "eiRegistrationInfo"
})
public abstract class EiRegistrationType {

    protected List<String> registreePartyID;
    @XmlElement(required = true)
    protected String registrarPartyID;
    @XmlElement(required = true)
    protected EiRegistrationInfoType eiRegistrationInfo;

    /**
     * Gets the value of the registreePartyID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the registreePartyID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegistreePartyID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRegistreePartyID() {
        if (registreePartyID == null) {
            registreePartyID = new ArrayList<String>();
        }
        return this.registreePartyID;
    }

    public boolean isSetRegistreePartyID() {
        return ((this.registreePartyID!= null)&&(!this.registreePartyID.isEmpty()));
    }

    public void unsetRegistreePartyID() {
        this.registreePartyID = null;
    }

    /**
     * Gets the value of the registrarPartyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrarPartyID() {
        return registrarPartyID;
    }

    /**
     * Sets the value of the registrarPartyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrarPartyID(String value) {
        this.registrarPartyID = value;
    }

    public boolean isSetRegistrarPartyID() {
        return (this.registrarPartyID!= null);
    }

    /**
     * Gets the value of the eiRegistrationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EiRegistrationInfoType }
     *     
     */
    public EiRegistrationInfoType getEiRegistrationInfo() {
        return eiRegistrationInfo;
    }

    /**
     * Sets the value of the eiRegistrationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EiRegistrationInfoType }
     *     
     */
    public void setEiRegistrationInfo(EiRegistrationInfoType value) {
        this.eiRegistrationInfo = value;
    }

    public boolean isSetEiRegistrationInfo() {
        return (this.eiRegistrationInfo!= null);
    }

}
