//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import ietf.params.xml.ns.icalendar_2_0.stream.StreamPayloadBaseType;


/**
 * Calculated Energy Baseline: A Baseline is an estimate of the electricity that would have been consumed by a Demand Resource in the absence of a Demand Response Event. The Baseline is compared to the actual metered electricity consumption during the Demand Response Event to determine the Demand Modification Value. Depending on the type of Demand Response product or service, Baseline calculations may be performed in real time or after the fact. Baseline may not be known at  time of event, in which case missing payload is used.
 * 
 * <p>Java class for EventBaselinePayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventBaselinePayloadType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ietf:params:xml:ns:icalendar-2.0:stream}StreamPayloadBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}payloadQuantity" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventBaselinePayloadType", propOrder = {
    "payloadQuantity"
})
public class EventBaselinePayloadType
    extends StreamPayloadBaseType
{

    protected PayloadQuantityType payloadQuantity;

    /**
     * Gets the value of the payloadQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link PayloadQuantityType }
     *     
     */
    public PayloadQuantityType getPayloadQuantity() {
        return payloadQuantity;
    }

    /**
     * Sets the value of the payloadQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayloadQuantityType }
     *     
     */
    public void setPayloadQuantity(PayloadQuantityType value) {
        this.payloadQuantity = value;
    }

    public boolean isSetPayloadQuantity() {
        return (this.payloadQuantity!= null);
    }

}
