//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ietf.params.xml.ns.icalendar_2.WsCalendarGluonType;


/**
 * Establishes relation between Active Interval of an Event and the Report Interval.
 * 
 * <p>Java class for EventGluonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventGluonType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/energyinterop/201110}ReportSchedulerBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}gluon" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}eventID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventGluonType", propOrder = {
    "gluon",
    "eventID"
})
public class EventGluonType
    extends ReportSchedulerBaseType
{

    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0")
    protected WsCalendarGluonType gluon;
    protected String eventID;

    /**
     * Used to establish relationship between Active Interval and Report Schedule. For example, SS -T30M and FF T1H would convey that the report runs from 30 minutes before the Active Period to one hour after. If absent, the Report Interval is equivalent to the Active Interval, i.e., the Report runs during Active Interval.
     * 
     * @return
     *     possible object is
     *     {@link WsCalendarGluonType }
     *     
     */
    public WsCalendarGluonType getGluon() {
        return gluon;
    }

    /**
     * Sets the value of the gluon property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsCalendarGluonType }
     *     
     */
    public void setGluon(WsCalendarGluonType value) {
        this.gluon = value;
    }

    public boolean isSetGluon() {
        return (this.gluon!= null);
    }

    /**
     * Indicates the Event this report is related to. If absent, must be delivered as part of a an EiEvent. 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventID(String value) {
        this.eventID = value;
    }

    public boolean isSetEventID() {
        return (this.eventID!= null);
    }

}
