//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReportEnumeratedType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReportEnumeratedType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="reading"/>
 *     &lt;enumeration value="usage"/>
 *     &lt;enumeration value="demand"/>
 *     &lt;enumeration value="setPoint"/>
 *     &lt;enumeration value="deltaUsage"/>
 *     &lt;enumeration value="deltaSetPoint"/>
 *     &lt;enumeration value="deltaDemand"/>
 *     &lt;enumeration value="baseline"/>
 *     &lt;enumeration value="deviation"/>
 *     &lt;enumeration value="avgUsage"/>
 *     &lt;enumeration value="avgDemand"/>
 *     &lt;enumeration value="operatingState"/>
 *     &lt;enumeration value="upRegulationCapacityAvailable"/>
 *     &lt;enumeration value="downRegulationCapacityAvailable"/>
 *     &lt;enumeration value="regulationSetpoint"/>
 *     &lt;enumeration value="storedEnergy"/>
 *     &lt;enumeration value="targetEnergyStorage"/>
 *     &lt;enumeration value="availableEnergyStorage"/>
 *     &lt;enumeration value="price"/>
 *     &lt;enumeration value="level"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReportEnumeratedType")
@XmlEnum
public enum ReportEnumeratedType {


    /**
     * Report indicates a Reading, as from a meter. Readings are moments in time--changes over time can be computed from the difference between successive readings. Payload Type is Float
     * 
     */
    @XmlEnumValue("reading")
    READING("reading"),

    /**
     * Report indicates an amount of units (denominated in Itembase or in the EMIX Product) over a period. Payload Type is Quantity. A typical ItemBase is Real Energy.
     * 
     */
    @XmlEnumValue("usage")
    USAGE("usage"),

    /**
     * Report indicates an amount of units (denominated in Itembase or in the EMIX Product). Payload Type is Quantity. A typical ItemBase is Real Power.
     * 
     */
    @XmlEnumValue("demand")
    DEMAND("demand"),

    /**
     * Report indicates the amount (denominated in Itembase or in the EMIX Product) currently set. May be a confirmation/return of the setpoint control value sent from the VTN. Payload Type is Quantity. A typical ItemBase is Real Power.
     * 
     */
    @XmlEnumValue("setPoint")
    SET_POINT("setPoint"),

    /**
     * Change in Usage as compared to the Baseline. See usage for more information
     * 
     */
    @XmlEnumValue("deltaUsage")
    DELTA_USAGE("deltaUsage"),

    /**
     * Changes in Setpoint from previous schedule.
     * 
     */
    @XmlEnumValue("deltaSetPoint")
    DELTA_SET_POINT("deltaSetPoint"),

    /**
     * Change in Demand as compared to the Baseline. See Demand for more information
     * 
     */
    @XmlEnumValue("deltaDemand")
    DELTA_DEMAND("deltaDemand"),

    /**
     * Can be Demand or Usage, as indicated by ItemBase. Indicates what [measurement[ would be if not for the Event or Regulation. Report is of the format Baseline.
     * 
     */
    @XmlEnumValue("baseline")
    BASELINE("baseline"),

    /**
     * Difference between some instruction and actual state.
     * 
     */
    @XmlEnumValue("deviation")
    DEVIATION("deviation"),

    /**
     * Average usage over the duration indicated by the Granularity. See usage for more information,
     * 
     */
    @XmlEnumValue("avgUsage")
    AVG_USAGE("avgUsage"),

    /**
     * Average usage over the duration indicated by the Granularity. See demand for more information.
     * 
     */
    @XmlEnumValue("avgDemand")
    AVG_DEMAND("avgDemand"),

    /**
     * Generalized state of a resource such as on/off, occupancy of building, etc. No ItemBase is relevant. Requires an Application Specific Payload Extension.
     * 
     */
    @XmlEnumValue("operatingState")
    OPERATING_STATE("operatingState"),

    /**
     * Up Regulation capacity available for dispatch, expressed in EMIX Real Power. Payload is always expressed as positive Quantity.
     * 
     */
    @XmlEnumValue("upRegulationCapacityAvailable")
    UP_REGULATION_CAPACITY_AVAILABLE("upRegulationCapacityAvailable"),

    /**
     * Down Regulation capacity available for dispatch, expressed in EMIX Real Power. Payload is always expressed as positive Quantity.
     * 
     */
    @XmlEnumValue("downRegulationCapacityAvailable")
    DOWN_REGULATION_CAPACITY_AVAILABLE("downRegulationCapacityAvailable"),

    /**
     * Regulation setpoint as instructed as part of regulation services
     * 
     */
    @XmlEnumValue("regulationSetpoint")
    REGULATION_SETPOINT("regulationSetpoint"),

    /**
     * Stored Energy is expressed as as Real Energy and Payload is expressed as a Quantity.
     * 
     */
    @XmlEnumValue("storedEnergy")
    STORED_ENERGY("storedEnergy"),

    /**
     * Target Energy is expressed as as Real Energy and Payload is expressed as a Quantity.
     * 
     */
    @XmlEnumValue("targetEnergyStorage")
    TARGET_ENERGY_STORAGE("targetEnergyStorage"),

    /**
     * Capacity available for further energy storage, perhaps to get to Target Energy Storage
     * 
     */
    @XmlEnumValue("availableEnergyStorage")
    AVAILABLE_ENERGY_STORAGE("availableEnergyStorage"),

    /**
     * Price per ItemBase at each Interval
     * 
     */
    @XmlEnumValue("price")
    PRICE("price"),

    /**
     * Simple level from market at each Interval. Itemabse is not relevant.
     * 
     */
    @XmlEnumValue("level")
    LEVEL("level");
    private final String value;

    ReportEnumeratedType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReportEnumeratedType fromValue(String v) {
        for (ReportEnumeratedType c: ReportEnumeratedType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
