//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import ietf.params.xml.ns.icalendar_2_0.stream.StreamPayloadBaseType;


/**
 * Report Payload for use in Reports, snaps, and projections.
 * 
 * <p>Java class for ReportPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportPayloadType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ietf:params:xml:ns:icalendar-2.0:stream}StreamPayloadBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}rID" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}confidence" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}readingType" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}accuracy" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}payloadBase"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportPayloadType", propOrder = {
    "rid",
    "confidence",
    "readingType",
    "accuracy",
    "payloadBase"
})
public class ReportPayloadType
    extends StreamPayloadBaseType
{

    @XmlElement(name = "rID")
    protected String rid;
    protected Long confidence;
    protected String readingType;
    protected Float accuracy;
    @XmlElementRef(name = "payloadBase", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110", type = JAXBElement.class)
    protected JAXBElement<? extends PayloadBaseType> payloadBase;

    /**
     * Gets the value of the rid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRID() {
        return rid;
    }

    /**
     * Sets the value of the rid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRID(String value) {
        this.rid = value;
    }

    public boolean isSetRID() {
        return (this.rid!= null);
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConfidence(Long value) {
        this.confidence = value;
    }

    public boolean isSetConfidence() {
        return (this.confidence!= null);
    }

    /**
     * Gets the value of the readingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadingType() {
        return readingType;
    }

    /**
     * Sets the value of the readingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadingType(String value) {
        this.readingType = value;
    }

    public boolean isSetReadingType() {
        return (this.readingType!= null);
    }

    /**
     * Gets the value of the accuracy property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAccuracy() {
        return accuracy;
    }

    /**
     * Sets the value of the accuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAccuracy(Float value) {
        this.accuracy = value;
    }

    public boolean isSetAccuracy() {
        return (this.accuracy!= null);
    }

    /**
     * Gets the value of the payloadBase property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PayloadPriceMultiplierType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadPriceRelativeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadBaseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadPriceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadApplicationSpecificType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadProductType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadQuantityType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadLevelType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadFloatType }{@code >}
     *     
     */
    public JAXBElement<? extends PayloadBaseType> getPayloadBase() {
        return payloadBase;
    }

    /**
     * Sets the value of the payloadBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PayloadPriceMultiplierType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadPriceRelativeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadBaseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadPriceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadApplicationSpecificType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadProductType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadQuantityType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadLevelType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadFloatType }{@code >}
     *     
     */
    public void setPayloadBase(JAXBElement<? extends PayloadBaseType> value) {
        this.payloadBase = value;
    }

    public boolean isSetPayloadBase() {
        return (this.payloadBase!= null);
    }

}
