//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Simple Levels are a set of simple indicators about scarcity and value, in which an ordered set of values indicate energy scarcity is above normal, normal, or below normal. Presumably, at higher levels, the VEN will use less.
 * 
 * <p>Java class for SimpleLevelContextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleLevelContextType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="levelNormalValue" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="levelUpperLimit" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleLevelContextType", propOrder = {
    "levelNormalValue",
    "levelUpperLimit"
})
public class SimpleLevelContextType {

    @XmlSchemaType(name = "unsignedInt")
    protected Long levelNormalValue;
    @XmlSchemaType(name = "unsignedInt")
    protected Long levelUpperLimit;

    /**
     * Gets the value of the levelNormalValue property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLevelNormalValue() {
        return levelNormalValue;
    }

    /**
     * Sets the value of the levelNormalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLevelNormalValue(Long value) {
        this.levelNormalValue = value;
    }

    public boolean isSetLevelNormalValue() {
        return (this.levelNormalValue!= null);
    }

    /**
     * Gets the value of the levelUpperLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLevelUpperLimit() {
        return levelUpperLimit;
    }

    /**
     * Sets the value of the levelUpperLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLevelUpperLimit(Long value) {
        this.levelUpperLimit = value;
    }

    public boolean isSetLevelUpperLimit() {
        return (this.levelUpperLimit!= null);
    }

}
