//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package net.opengis.gml.v_3_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class GeodeticDatumUpperCase
    extends JAXBElement<GeodeticDatumType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/gml/3.2", "GeodeticDatum");

    public GeodeticDatumUpperCase(GeodeticDatumType value) {
        super(NAME, ((Class) GeodeticDatumType.class), null, value);
    }

    public GeodeticDatumUpperCase() {
        super(NAME, ((Class) GeodeticDatumType.class), null, null);
    }

}
