//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package net.opengis.gml.v_3_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class ParameterValueUpperCase
    extends JAXBElement<ParameterValueType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/gml/3.2", "ParameterValue");

    public ParameterValueUpperCase(ParameterValueType value) {
        super(NAME, ((Class) ParameterValueType.class), null, value);
    }

    public ParameterValueUpperCase() {
        super(NAME, ((Class) ParameterValueType.class), null, null);
    }

}
