//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.MaximumEnergyType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.MaximumPowerType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.MinimumLoadReductionType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.MinimumLoadType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.OfferCurveType;
import org.oasis_open.docs.ns.energyinterop._201110.EiResponseSmoothingType;


/**
 * Collection of Emix Terms
 * 
 * <p>Java class for ArrayOfTerms complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfTerms">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}baseTerm" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfTerms", propOrder = {
    "baseTerm"
})
public class ArrayOfTerms {

    @XmlElementRef(name = "baseTerm", namespace = "http://docs.oasis-open.org/ns/emix/2011/06", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends BaseTermType>> baseTerm;

    /**
     * Gets the value of the baseTerm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseTerm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseTerm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link OfferCurveType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumRunDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumDurationBetweenInvocationsType }{@code >}
     * {@link JAXBElement }{@code <}{@link RequiredStartupRemunerationType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResponseTimeType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaximumResponseDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumLoadType }{@code >}
     * {@link JAXBElement }{@code <}{@link BaseTermType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaximumPowerType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaximumInvocationsPerDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link MarketGranularityType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaximumNotificationDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaximumRunDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumResponseDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumStartsPerDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link EiResponseSmoothingType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumEconomicRequirementType }{@code >}
     * {@link JAXBElement }{@code <}{@link NotificationScheduleType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumLoadReductionType }{@code >}
     * {@link JAXBElement }{@code <}{@link AvailabilityScheduleType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaximumConsecutiveDurationsType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumRecoveryDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaximumEnergyType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumRemunerationRateType }{@code >}
     * {@link JAXBElement }{@code <}{@link MinimumNotificationDurationType }{@code >}
     * {@link JAXBElement }{@code <}{@link UnavailabilityScheduleType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends BaseTermType>> getBaseTerm() {
        if (baseTerm == null) {
            baseTerm = new ArrayList<JAXBElement<? extends BaseTermType>>();
        }
        return this.baseTerm;
    }

    public boolean isSetBaseTerm() {
        return ((this.baseTerm!= null)&&(!this.baseTerm.isEmpty()));
    }

    public void unsetBaseTerm() {
        this.baseTerm = null;
    }

}
