//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.power.PowerQualityWarrantType;


/**
 * Collection of Emix Warrants
 * 
 * <p>Java class for ArrayOfWarrants complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfWarrants">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}baseWarrant" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfWarrants", propOrder = {
    "baseWarrant"
})
public class ArrayOfWarrants {

    @XmlElementRef(name = "baseWarrant", namespace = "http://docs.oasis-open.org/ns/emix/2011/06", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends BaseWarrantType>> baseWarrant;

    /**
     * Gets the value of the baseWarrant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseWarrant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseWarrant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PowerQualityWarrantType }{@code >}
     * {@link JAXBElement }{@code <}{@link EnvironmentalWarrantType }{@code >}
     * {@link JAXBElement }{@code <}{@link SupportForPriceType }{@code >}
     * {@link JAXBElement }{@code <}{@link QualityWarrantType }{@code >}
     * {@link JAXBElement }{@code <}{@link BaseWarrantType }{@code >}
     * {@link JAXBElement }{@code <}{@link SourceWarrantType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends BaseWarrantType>> getBaseWarrant() {
        if (baseWarrant == null) {
            baseWarrant = new ArrayList<JAXBElement<? extends BaseWarrantType>>();
        }
        return this.baseWarrant;
    }

    public boolean isSetBaseWarrant() {
        return ((this.baseWarrant!= null)&&(!this.baseWarrant.isEmpty()));
    }

    public void unsetBaseWarrant() {
        this.baseWarrant = null;
    }

}
