//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.MaximumEnergyType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.MaximumPowerType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.MinimumLoadReductionType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.MinimumLoadType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.OfferCurveType;
import org.oasis_open.docs.ns.energyinterop._201110.EiResponseSmoothingType;


/**
 * Type of Abstract extension object for Emix Terms
 * 
 * <p>Java class for BaseTermType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseTermType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseTermType")
@XmlSeeAlso({
    EiResponseSmoothingType.class,
    OfferCurveType.class,
    MaximumPowerType.class,
    MinimumLoadType.class,
    MaximumEnergyType.class,
    MinimumLoadReductionType.class,
    MinimumStartsPerDurationType.class,
    MaximumNotificationDurationType.class,
    NotificationScheduleType.class,
    MaximumRunDurationType.class,
    MinimumDurationBetweenInvocationsType.class,
    RequiredStartupRemunerationType.class,
    MaximumResponseDurationType.class,
    MinimumResponseDurationType.class,
    MarketGranularityType.class,
    UnavailabilityScheduleType.class,
    AvailabilityScheduleType.class,
    MinimumRunDurationType.class,
    MaximumInvocationsPerDurationType.class,
    MaximumConsecutiveDurationsType.class,
    MinimumNotificationDurationType.class,
    ResponseTimeType.class,
    MinimumRecoveryDurationType.class,
    MinimumRemunerationRateType.class,
    MinimumEconomicRequirementType.class
})
public abstract class BaseTermType {


}
