//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import ietf.params.xml.ns.icalendar_2.VcalendarType;


/**
 * 
 * 			iCalendar-derived object to host EMIX elements
 * 
 * <p>Java class for EmixBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmixBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ietf:params:xml:ns:icalendar-2.0}VcalendarType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}uid"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}envelopeContents" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmixBaseType", propOrder = {
    "uid",
    "envelopeContents"
})
@XmlSeeAlso({
    DeliveryType.class,
    ProductType.class,
    EmixOptionType.class
})
public abstract class EmixBaseType
    extends VcalendarType
{

    @XmlElement(required = true)
    protected String uid;
    protected EnvelopeContentsType envelopeContents;

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    public boolean isSetUid() {
        return (this.uid!= null);
    }

    /**
     * Gets the value of the envelopeContents property.
     * 
     * @return
     *     possible object is
     *     {@link EnvelopeContentsType }
     *     
     */
    public EnvelopeContentsType getEnvelopeContents() {
        return envelopeContents;
    }

    /**
     * Sets the value of the envelopeContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvelopeContentsType }
     *     
     */
    public void setEnvelopeContents(EnvelopeContentsType value) {
        this.envelopeContents = value;
    }

    public boolean isSetEnvelopeContents() {
        return (this.envelopeContents!= null);
    }

}
