//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.power.AggregatedPnodeType;
import org.oasis_open.docs.ns.emix._2011._06.power.EndDeviceAssetType;
import org.oasis_open.docs.ns.emix._2011._06.power.MeterAssetType;
import org.oasis_open.docs.ns.emix._2011._06.power.PnodeType;
import org.oasis_open.docs.ns.emix._2011._06.power.ServiceDeliveryPointType;
import org.oasis_open.docs.ns.emix._2011._06.power.ServiceLocationType;
import org.oasis_open.docs.ns.emix._2011._06.power.TransportInterfaceType;


/**
 * Abstract base class for the interfaces for EMIX Product delivery, measurement, and/or pricing
 * 
 * <p>Java class for EmixInterfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmixInterfaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmixInterfaceType")
@XmlSeeAlso({
    ServiceAreaType.class,
    ServiceLocationType.class,
    ServiceDeliveryPointType.class,
    EndDeviceAssetType.class,
    MeterAssetType.class,
    PnodeType.class,
    TransportInterfaceType.class,
    AggregatedPnodeType.class
})
public abstract class EmixInterfaceType {


}
