//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.oasis_open.docs.ns.emix._2011._06.power.AncillaryServiceType;
import un.unece.uncefact.codelist.standard._5.iso42173a._2010_04_07.ISO3AlphaCurrencyCodeContentType;


/**
 * <p>Java class for EmixOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmixOptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/emix/2011/06}EmixBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}transactiveState"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}expirationDate" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}integralOnly" minOccurs="0"/>
 *         &lt;element name="optionHolderSide" type="{http://docs.oasis-open.org/ns/emix/2011/06}SideType"/>
 *         &lt;element name="optionPremium" type="{http://docs.oasis-open.org/ns/emix/2011/06}PriceType"/>
 *         &lt;element name="optionStrikePrice" type="{http://docs.oasis-open.org/ns/emix/2011/06}PriceType"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}optionType"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}side"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}marketContext"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}currency" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}terms" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmixOptionType", propOrder = {
    "transactiveState",
    "expirationDate",
    "integralOnly",
    "optionHolderSide",
    "optionPremium",
    "optionStrikePrice",
    "optionType",
    "side",
    "marketContext",
    "currency",
    "terms"
})
@XmlSeeAlso({
    AncillaryServiceType.class
})
public class EmixOptionType
    extends EmixBaseType
{

    @XmlElement(required = true)
    protected TransactiveStateType transactiveState;
    protected XMLGregorianCalendar expirationDate;
    protected Boolean integralOnly;
    @XmlElement(required = true)
    protected SideType optionHolderSide;
    @XmlElement(required = true)
    protected PriceType optionPremium;
    @XmlElement(required = true)
    protected PriceType optionStrikePrice;
    @XmlElement(required = true)
    protected String optionType;
    @XmlElement(required = true)
    protected SideType side;
    @XmlElement(required = true)
    protected String marketContext;
    protected ISO3AlphaCurrencyCodeContentType currency;
    protected ArrayOfTerms terms;

    /**
     * Gets the value of the transactiveState property.
     * 
     * @return
     *     possible object is
     *     {@link TransactiveStateType }
     *     
     */
    public TransactiveStateType getTransactiveState() {
        return transactiveState;
    }

    /**
     * Sets the value of the transactiveState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactiveStateType }
     *     
     */
    public void setTransactiveState(TransactiveStateType value) {
        this.transactiveState = value;
    }

    public boolean isSetTransactiveState() {
        return (this.transactiveState!= null);
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    public boolean isSetExpirationDate() {
        return (this.expirationDate!= null);
    }

    /**
     * If true, each Option Call must be for the full amount specified
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntegralOnly() {
        return integralOnly;
    }

    /**
     * Sets the value of the integralOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntegralOnly(Boolean value) {
        this.integralOnly = value;
    }

    public boolean isSetIntegralOnly() {
        return (this.integralOnly!= null);
    }

    /**
     * Gets the value of the optionHolderSide property.
     * 
     * @return
     *     possible object is
     *     {@link SideType }
     *     
     */
    public SideType getOptionHolderSide() {
        return optionHolderSide;
    }

    /**
     * Sets the value of the optionHolderSide property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideType }
     *     
     */
    public void setOptionHolderSide(SideType value) {
        this.optionHolderSide = value;
    }

    public boolean isSetOptionHolderSide() {
        return (this.optionHolderSide!= null);
    }

    /**
     * Gets the value of the optionPremium property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getOptionPremium() {
        return optionPremium;
    }

    /**
     * Sets the value of the optionPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setOptionPremium(PriceType value) {
        this.optionPremium = value;
    }

    public boolean isSetOptionPremium() {
        return (this.optionPremium!= null);
    }

    /**
     * Gets the value of the optionStrikePrice property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getOptionStrikePrice() {
        return optionStrikePrice;
    }

    /**
     * Sets the value of the optionStrikePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setOptionStrikePrice(PriceType value) {
        this.optionStrikePrice = value;
    }

    public boolean isSetOptionStrikePrice() {
        return (this.optionStrikePrice!= null);
    }

    /**
     * Gets the value of the optionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionType() {
        return optionType;
    }

    /**
     * Sets the value of the optionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionType(String value) {
        this.optionType = value;
    }

    public boolean isSetOptionType() {
        return (this.optionType!= null);
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link SideType }
     *     
     */
    public SideType getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideType }
     *     
     */
    public void setSide(SideType value) {
        this.side = value;
    }

    public boolean isSetSide() {
        return (this.side!= null);
    }

    /**
     * Gets the value of the marketContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketContext() {
        return marketContext;
    }

    /**
     * Sets the value of the marketContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketContext(String value) {
        this.marketContext = value;
    }

    public boolean isSetMarketContext() {
        return (this.marketContext!= null);
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link ISO3AlphaCurrencyCodeContentType }
     *     
     */
    public ISO3AlphaCurrencyCodeContentType getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISO3AlphaCurrencyCodeContentType }
     *     
     */
    public void setCurrency(ISO3AlphaCurrencyCodeContentType value) {
        this.currency = value;
    }

    public boolean isSetCurrency() {
        return (this.currency!= null);
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTerms }
     *     
     */
    public ArrayOfTerms getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTerms }
     *     
     */
    public void setTerms(ArrayOfTerms value) {
        this.terms = value;
    }

    public boolean isSetTerms() {
        return (this.terms!= null);
    }

}
