//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import ietf.params.xml.ns.icalendar_2.ArtifactBaseType;
import org.oasis_open.docs.ns.emix._2011._06.power.PowerProductDescriptionType;
import org.oasis_open.docs.ns.emix._2011._06.power.TemixPowerType;
import org.oasis_open.docs.ns.emix._2011._06.power.resource.ResourceDescriptionType;


/**
 * In EMIX, the Product Description is placed in the Interval or Gluon attachment. The respective product schemas extend this abstract class.
 * 
 * <p>Java class for ProductDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductDescriptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ietf:params:xml:ns:icalendar-2.0}ArtifactBaseType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductDescriptionType")
@XmlSeeAlso({
    ResourceDescriptionType.class,
    MeasurementType.class,
    TemixPowerType.class,
    PowerProductDescriptionType.class
})
public abstract class ProductDescriptionType
    extends ArtifactBaseType
{


}
