//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 11:06:51 AM PST 
//


package org.oasis_open.docs.ns.emix._2011._06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ietf.params.xml.ns.icalendar_2.VavailabilityType;


/**
 * A collection of Standard Terms for this market
 * 
 * <p>Java class for StandardTermsSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StandardTermsSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}terms"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}vavailability" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}nonStandardTermsHandling"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}side" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardTermsSetType", propOrder = {
    "terms",
    "vavailability",
    "nonStandardTermsHandling",
    "side"
})
public class StandardTermsSetType {

    @XmlElement(required = true)
    protected ArrayOfTerms terms;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0")
    protected VavailabilityType vavailability;
    @XmlElement(required = true)
    protected NonStandardTermsHandlingType nonStandardTermsHandling;
    protected SideType side;

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTerms }
     *     
     */
    public ArrayOfTerms getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTerms }
     *     
     */
    public void setTerms(ArrayOfTerms value) {
        this.terms = value;
    }

    public boolean isSetTerms() {
        return (this.terms!= null);
    }

    /**
     * If present, this defines the period(s) that this RuleSet applies to, i.e., weekdays 9:00-5:00.
     * 
     * @return
     *     possible object is
     *     {@link VavailabilityType }
     *     
     */
    public VavailabilityType getVavailability() {
        return vavailability;
    }

    /**
     * Sets the value of the vavailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link VavailabilityType }
     *     
     */
    public void setVavailability(VavailabilityType value) {
        this.vavailability = value;
    }

    public boolean isSetVavailability() {
        return (this.vavailability!= null);
    }

    /**
     * Gets the value of the nonStandardTermsHandling property.
     * 
     * @return
     *     possible object is
     *     {@link NonStandardTermsHandlingType }
     *     
     */
    public NonStandardTermsHandlingType getNonStandardTermsHandling() {
        return nonStandardTermsHandling;
    }

    /**
     * Sets the value of the nonStandardTermsHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonStandardTermsHandlingType }
     *     
     */
    public void setNonStandardTermsHandling(NonStandardTermsHandlingType value) {
        this.nonStandardTermsHandling = value;
    }

    public boolean isSetNonStandardTermsHandling() {
        return (this.nonStandardTermsHandling!= null);
    }

    /**
     * Some terms may have different interpretation as to side. A Buyer term may indicate "meet or exceed" well a seller expressing the same term may indicate "no worse than".
     * 
     * @return
     *     possible object is
     *     {@link SideType }
     *     
     */
    public SideType getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideType }
     *     
     */
    public void setSide(SideType value) {
        this.side = value;
    }

    public boolean isSetSide() {
        return (this.side!= null);
    }

}
